# Generated by Django 6.0.7 on 2026-07-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0002_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('weather', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
