# Generated by Django 6.0.7 on 2026-07-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0003_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
