# Generated by Django 6.0.7 on 2026-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0004_alter_weather_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='weather_code',
            field=models.IntegerField(default=0),
        ),
    ]
