# Generated by Django 6.0.7 on 2026-07-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0006_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
