# Generated by Django 6.0.7 on 2026-07-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0008_task_id_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
