# Generated by Django 6.0.7 on 2026-08-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0011_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
