# Generated by Django 6.0.7 on 2026-08-12 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0013_alter_task_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='ticket_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('chore', 'Chore')], default='feature', max_length=10),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('github_repo', models.CharField(help_text="e.g. 'owner/repository'", max_length=200)),
                ('ast_outline', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='coresite.project'),
        ),
    ]
