# Generated by Django 6.0.7 on 2026-08-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0014_task_subtasks_task_ticket_type_project_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
