# Generated by Django 6.0.7 on 2026-08-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0015_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_token',
            field=models.CharField(blank=True, default='', help_text='GitHub personal access token for private repos', max_length=500),
        ),
    ]
