# Generated by Django 6.0.7 on 2026-08-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0016_project_github_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_repo',
            field=models.CharField(blank=True, default='', help_text="e.g. 'owner/repository'", max_length=200),
        ),
    ]
